export const Action_Types = {
    FETCH_API_PRODUCTS : "FETCH_API_PRODUCTS", 
    SET_PRODUCTS : "SET_PRODUCTS",
    FETCH_SELECTED_PRODUCT : "FETCH_SELECTED_PRODUCT",
    DELETE_SELECTED_PRODUCT : "DELETE_SELECTED_PRODUCT"
}